### ISSUE TITLE
display token usage and session cost in frontend

### ISSUE THREAD

**Issue by K-Schubert** [CdC-SI/ZAS-EAK-CopilotGPT#398]
**Description**

- Display token usage and session cost in USD/CHF in frontend.
- Get information with `GET` request to `/apy/usage` endpoint:
```
RequestModel:
    user_uuid: str
    conversation_uuid: str

ResponseModel:
    tokens_consumed: int
    cost_usd: float
    cost_chf: float
```
